Use LBYL instead of EAFP in directory creation in setup_environment.py
open-power-host-os/builds pull request #133
Opened 2016-12-22 14:14 UTC by alanoe

Newer code is simpler. The only disadvantage is that it
is not thread-safe, but this code will never be run concurrently,
so this is not an issue.

2016-12-22 14:31 UTC, ghost approved these changes

2016-12-22 16:15 UTC, gyribeiro approved these changes

2016-12-22 19:09 UTC, olavphibm commented
start tests

2016-12-23 12:29 UTC, ghost requested changes

2016-12-23 12:29 UTC, olavphibm commented on tools/setup_environment.py
> +    if not os.path.exists(directory):
Use `os.path.isdir` here, `exists` would allow a file with this name.

2016-12-23 15:06 UTC, olavphibm commented
start tests

2016-12-23 15:06 UTC, ghost approved these changes

2016-12-23 18:55 UTC, merged