Make archive sub attrib optional in packages sources attributes in package YAML file
open-power-host-os/builds pull request #134
Opened 2016-12-23 18:48 UTC by alanoe

2016-12-23 19:11 UTC, snowcrshd commented on lib/repository.py
> +        match_obj = re.match(".*/([a-zA-Z0-9\-]*)\.git", remote_repo_url)
Won't this break if the repository name is some weird string?

There are some [special characters that are allowed in a URL](http://stackoverflow.com/questions/1856785/characters-allowed-in-a-url#1856809) that could show up in the repository's name.

2016-12-23 19:13 UTC, ghost requested changes
I'd rather not pass in 'None' into all those function calls, just to have an 'if' checking if the name was provided.

Better to just remove the 'name' parameter and either infer it or fail noisily.

2016-12-23 19:20 UTC, olavphibm commented on lib/repository.py
> +        match_obj = re.match(".*/([a-zA-Z0-9\-]*)\.git", remote_repo_url)
I'd use `urlparse` combined with `os.path.basename` for that.

2016-12-23 19:23 UTC, olavphibm commented
start build

2016-12-23 19:40 UTC, olavphibm commented
I'm with either removing the "name" parameter completely, or leaving it as a keyword arg, so we don't have to pass `None` every time.

2016-12-23 20:09 UTC, olavphibm commented
start build

2016-12-23 21:16 UTC, alanoe commented on lib/repository.py
> +        match_obj = re.match(".*/([a-zA-Z0-9\-]*)\.git", remote_repo_url)
imho [a-zA-Z0-9\-_]* is a safe regex, I have never seen other chars in source code repositories names

2016-12-23 21:17 UTC, alanoe commented
OH> I'm with either removing the "name" parameter completely, or leaving it as a keyword arg, so we don't have to pass None every time.

Agreed. I see no reason to have this argument in our build code, so I'll remove it.

2016-12-26 11:20 UTC, ghost requested changes

2016-12-26 11:20 UTC, olavphibm commented on lib/repository.py
> +    name = os.path.basename(url_parts.path)
This name might have a ".git" that we need to remove.

2016-12-26 11:20 UTC, olavphibm commented on lib/repository.py
> +    Get a local git repository located in a subdirectory of the parent directory.
You could mention it is "named after the base name of the URL path"

2016-12-26 11:20 UTC, olavphibm commented on lib/versions_repository.py
> +    path, _ = os.path.split(
`os.path.dirname` could be used here instead of `split`

2016-12-26 19:32 UTC, alanoe commented on lib/versions_repository.py
> +    path, _ = os.path.split(
I prefer to not alter how parent directory path is obtained in this patch. This is an improvement which could be done in a separate patch.

2016-12-26 19:32 UTC, alanoe commented on lib/repository.py
> +    name = os.path.basename(url_parts.path)
Done

2016-12-26 19:32 UTC, alanoe commented on lib/repository.py
> +    Get a local git repository located in a subdirectory of the parent directory.
Done

2017-01-05 08:21 UTC, snowcrshd commented on lib/repository.py
> +    name = os.path.basename(url_parts.path)
I think that `# infer name` could be removed.

It doesn't add much information to that context. It ends up being just noise in the source code.

2017-01-06 17:14 UTC, fabianorosas commented
start build

2017-01-06 21:42 UTC, alanoe commented
start build

2017-01-09 12:57 UTC, snowcrshd commented on lib/repository.py
> +    # infer name
Please remove this comment, it doesn't add meaningful information.

2017-01-09 14:59 UTC, snowcrshd commented
start build

2017-01-10 16:57 UTC, ghost approved these changes

2017-01-10 17:07 UTC, olavphibm commented
start build

2017-01-10 19:21 UTC, fabianorosas commented
This relates to #38

2017-01-10 20:37 UTC, alanoe commented on lib/repository.py
> +    # infer name
IMHO considering a comment to be obvious (and thus useless) or not is usually a matter of personal taste. Very minor issue IMHO. Anyway, I have updated the comment to make it more useful.

2017-01-10 20:40 UTC, alanoe commented
Pls let us merge this ASAP so I do not need to rebase this patch again.

2017-01-11 10:45 UTC, ghost approved these changes

2017-01-11 10:46 UTC, merged