Document how to contribute a new package to Host OS
open-power-host-os/builds pull request #160
Opened 2017-01-25 19:40 UTC by lisibann

2017-01-26 18:54 UTC, alanoe requested changes

2017-01-26 18:54 UTC, alanoe commented on README.rst
> +
As we talked personally today, simply point to documentation in the versions git repository from here and add this text there.

2017-01-26 18:54 UTC, alanoe commented on README.rst
> +1. Create a metadata file <package_name>.yaml. It will contain most of the information required to build the package. The package metadata (yaml) file format is at https://github.com/open-power-host-
metadata file => metadata file named

2017-01-26 18:54 UTC, alanoe commented on README.rst
> +1. Create a metadata file <package_name>.yaml. It will contain most of the information required to build the package. The package metadata (yaml) file format is at https://github.com/open-power-host-
As we discussed today, I'll rename the file to package_metadata_yaml_template.yaml . Rename it here

2017-01-26 18:54 UTC, alanoe commented on README.rst
> +2. Create subdirectory "centOS/7", current "Linux Distribution Name"/"Linux Distribution Version", respectively
=> Create two subdirectories named <distro_name> and <distro_name>/distro_version>, eg CentOS and CentOS/7

2017-01-26 18:54 UTC, alanoe commented on README.rst
> +3. Create rpm package specification file under <package_name>/centOS/7
=> Create a rpm ackage specification file in <package_name>/<distro_name>/<distro_version>/<package_name>.spec

2017-01-26 18:54 UTC, alanoe commented on README.rst
> +4. Create (copy) the files required to build the package under <package_name>/centOS/7/SOURCES
=> Copy the files required to build the package to <package_name>/<distro_name>/<distro_version>/SOURCES/

2017-01-26 18:54 UTC, alanoe commented on README.rst
> +When using %check stage at specification file, add macro to make possible to skip tests (check phase)
You are using "stage" and "phase" for the same concept, pls be consistent in terminology.

=> If the rpm specification file has a %check macro for running tests during rpm package build, add the following code to allow skipping these tests

2017-01-26 18:54 UTC, alanoe commented on README.rst
> +2. Add at the point of check stage:
stage => macro

2017-01-31 13:43 UTC, fabianorosas commented
I'd put this doc in the CONTRIBUTING.rst file. Regular usage of the repository does not require creating new packages.

2017-02-01 12:37 UTC, lisibann commented on README.rst
> +2. Add at the point of check stage:
Thanks Alan. I'll apply all these changes.

2017-02-01 12:38 UTC, lisibann commented
I'll move documentation text to CONTRIBUTION.rst files on both builds and versions repositories.

2017-02-01 13:57 UTC, alanoe commented
LA> I'll move documentation text to CONTRIBUTION.rst files on both builds and versions repositories.

Pls do not keep duplicated content on both files. The one in builds git repository should reference the one in versions git repository.

2017-02-01 15:50 UTC, olavphibm commented on CONTRIBUTING.rst
> +<https://github.com/open-power-host-os/versions>`_.
My understanding is that the `Contributing code` section refers to contributing with the Python scripts used in the builds.
I'd create a new section `Contributing packages` and write something like:
For details on adding new packages to the project, refer to the `versions repository documentation <link to specific documentation>`_

2017-02-01 15:51 UTC, lisibann commented
Yes. The builds/CONTRIBUTING.rst refers to versions.

2017-02-01 16:07 UTC, lisibann commented on CONTRIBUTING.rst
> +<https://github.com/open-power-host-os/versions>`_.
Done.

2017-02-02 12:30 UTC, olavphibm commented on CONTRIBUTING.rst
> +<https://github.com/open-power-host-os/versions>`_.
Place a link directly to the contributing page: `https://github.com/open-power-host-os/versions/blob/master/CONTRIBUTING.rst`

2017-02-08 13:42 UTC, lisibann commented on CONTRIBUTING.rst
> +<https://github.com/open-power-host-os/versions>`_.
done

2017-02-09 04:02 UTC, alanoe approved these changes

2017-02-09 15:45 UTC, ghost approved these changes

2017-02-10 10:55 UTC, merged