Modify upgrade-versions to allow its usage without push-repo parameters
open-power-host-os/builds pull request #173
Opened 2017-02-01 22:35 UTC by lisibann

2017-02-02 11:22 UTC, ghost requested changes

2017-02-02 11:22 UTC, olavphibm commented on tools/upgrade_versions.py
> +    REQUIRED_PUSH_REPO_PARAMETERS = ["push_repo_url", "push_repo_branch"]
I'd remove the `REQUIRED_` prefix, since those parameters are now optional.

2017-02-02 11:22 UTC, olavphibm commented on tools/upgrade_versions.py
> +    push_repo = True
What if we got this boolean from the config? This way, the user would have to explicitly disable pushing (e.g. by passing --local-update) and we could just concatenate the list `PUSH_REPO_PARAMETERS` into `REQUIRED_PARAMETERS` if it's `True`, removing the second for.

2017-02-02 11:22 UTC, olavphibm commented on tools/upgrade_versions.py
> +                          push_repo_branch, committer_name, committer_email)
We still want a local commit, so either we put this if inside the `push_new_versions` function or split into two, e.g. `create_commit` and `push_new_versions`. I think the latter will look better.
This local commit will then have to be passed to the `build_host_os` job in the nightly job.

2017-02-02 11:22 UTC, olavphibm commented on lib/config.py
> -        [PUSH_REPO_ARGS, BUILD_REPO_ARGS]),
Please explain the motivation in the commit longer message. I believe you want to select the packages that are being upgraded?

2017-02-02 19:27 UTC, alanoe commented
It seems that I and Lisiane have developed the same feature by accident. My PR #174 handles the same problem and already implements most changes suggested by Olav here. I suggest we use it and close this one.

2017-02-03 16:06 UTC, olavphibm commented
This is already being implemented in https://github.com/open-power-host-os/builds/pull/174

2017-02-03 16:06 UTC, closed without merging