Add documentation about how to build old versions
open-power-host-os/builds pull request #187
Opened 2017-02-15 16:17 UTC by alanoe

2017-02-15 19:39 UTC, olavphibm commented on README.rst
> +These steps are documented in jenkins_jobs/build_old_host_os_versions/script.sh in the
You could place a direct link to the file here.

2017-02-15 19:40 UTC, alanoe commented on README.rst
> +These steps are documented in jenkins_jobs/build_old_host_os_versions/script.sh in the
Done

2017-02-17 13:25 UTC, farosas requested changes

2017-02-17 13:25 UTC, fabianorosas commented on README.rst
> + * Replace build_version in config.yaml to v1.5.0 or v1.0.0
I think we should improve the presentation of this info. Some points:

1- the nested bullets are ugly in GitHub 
2- there is too much text. E.g. in first bullet, the reader needs to visually parse both mirror links before getting to the name of the file that needs to be edited
3- too many non-alphabetical characters make it harder to read

I suggest a more concise text, without nesting and providing commands to copy/paste:

---
* Build old versions

OpenPOWER Host OS 1.0 and 1.5 used an older CentOS (7.2) as base version. 

Change yum mirror to CentOS 7.2
```
$ sed -i 's!http://mirror.centos.org/altarch/7!http://vault.centos.org/altarch/7.2.1511/!' mock_configs/CentOS/7/CentOS-7-ppc64le.cfg
```

Change the distro version to 7.2
```
$ sed -i "s/'7'/'7.2'/g" config.yaml 
```

Inform which version to build
```
$ sed -i "s/build_version:.*/build_version: 'v1.5.0'/" config.yaml # use v1.5.0 or v1.0.0
```

---
*note: the seds might be improved a bit*
*note 2: I realize the second command hides two actions in one and that we have to be careful with replacing '7', but I think it's worth it.*

2017-02-21 19:06 UTC, alanoe commented on README.rst
> + * Replace build_version in config.yaml to v1.5.0 or v1.0.0
OK for me. I just prefer to use 2 more explicit seds then the one you use to update the distro version.

2017-02-23 19:20 UTC, farosas requested changes

2017-02-23 19:20 UTC, fabianorosas commented on README.rst
> +Update yum repository to CentOS 7.2
missing :: in all entries

2017-02-23 19:28 UTC, alanoe commented on README.rst
> +Update yum repository to CentOS 7.2
Done

2017-02-23 20:37 UTC, merged