Document how to build custom software
open-power-host-os/builds pull request #193
Opened 2017-02-21 22:12 UTC by alanoe

2017-02-23 18:05 UTC, farosas requested changes

2017-02-23 18:05 UTC, farosas commented on README.rst
> +
I see no reason to have the two formats documented in the README, this is very obvious. If you want make it clear that spaces need to be used just add ' kernel' to line 75. The user will be capable of inferring that removing the word 'kernel' signifies to build only 'libvirt' and likewise for adding words to the list.

2017-02-23 18:05 UTC, farosas commented on README.rst
> +The build code keeps a cache of all source code management (Git, Mercurial, SVN)
I suggest `s/all source code management (Git, Mercurial, SVN)/packages/`. It makes it easier to grasp the meaning of the phrase. For a moment I thought we keep a cache of Git's source code somewhere.

2017-02-23 18:05 UTC, fabianorosas commented on README.rst
> +repository content. To build the package from the custom content, either use a
`s/custom content/modified repository/`

2017-02-23 18:05 UTC, fabianorosas commented on README.rst
> +file:// URL pointing to the local repository in the package metadata (YAML)
`s/the local repository/it/`

2017-03-03 20:34 UTC, alanoe commented on README.rst
> +The build code keeps a cache of all source code management (Git, Mercurial, SVN)
"packages repositories" may be confused with yum repositories, as "repository" is a generic term used by VCS (git/mercurial/svn) and Linux packages management systems (yum/aptitude/zypper). I used "packages source code (Git/Mercurial/SVN) repositories", hope that has became more obvious to interpret.

2017-03-03 20:35 UTC, alanoe commented on README.rst
> +repository content. To build the package from the custom content, either use a
"custom" and "modified" mean the same thing... but ok

2017-03-03 20:35 UTC, alanoe commented on README.rst
> +
Done

2017-03-03 20:37 UTC, alanoe commented on README.rst
> +file:// URL pointing to the local repository in the package metadata (YAML)
"it" would be confusing in this context IMHO. A reader would not know if it means "package", "custom content" or "local repository"

2017-03-03 20:55 UTC, farosas approved these changes

2017-03-03 21:21 UTC, olavphibm commented
start build

2017-03-04 22:21 UTC, ghost approved these changes

2017-03-04 22:24 UTC, merged