Support overriding package source code repositories data in command line
open-power-host-os/builds pull request #207
Opened 2017-03-07 19:18 UTC by alanoe

2017-03-08 20:43 UTC, lisibann approved these changes

2017-03-09 18:27 UTC, mopsfelder commented on lib/package.py
> +                    package_parts = package.split("#")
I think adding a comment here describing the expected format helps.  For example:

```python
# Parse and set package source attributes from the command line.
# Fields are separated by `#` character and the expected format
# can be one of the following:
#
#     package_name#repo_url#branch_name#revision_id
#     package_name#repo_url#reference
#     package_name##reference
#     package_name

package_parts = package.split("#")
...
```

2017-03-09 21:06 UTC, ghost requested changes

2017-03-09 21:06 UTC, ghost commented on lib/package.py
> +                    package_parts = package.split("#")
I think this format should also be in the help of the "packages" option.

2017-03-09 21:06 UTC, ghost commented on lib/package.py
> +            if package.startswith(name):
This could cause a problem with ginger and ginger-base, for example. You should split the parts before this check.

2017-03-09 21:06 UTC, ghost commented on tools/build_packages.py
> +        packages_to_build_names.append(package.split("#")[0])
This must also be done for update-versions, unless we want to break consistency of the command line option and mention the differences in the help message.

2017-03-09 21:06 UTC, olavphibm commented on lib/package.py
> +                           self.sources[0][source_type]["commit_id"] = package_parts[2]
I find it a little hard to follow the code with the nested ifs and indexes everywhere.
I know you're not a fan of EAFP, but here's a suggestion. The try block stops when it finds an undefined variable. Feel free to keep as is if you dislike it.
```
package_parts = package.split("#")
if len(package_parts) == 1:
    break
elif len(package_parts) == 2:
    _, src = package_parts
elif len(package_parts) == 3:
    _, src, commit_id = package_parts
elif len(package_parts) == 4:
    _, src, branch, commit_id = package_parts
else:
    raise "Too many parts"
try:
    if src:
       self.sources[0][source_type]["src"] = src
    if commit_id:
       self.sources[0][source_type]["commit_id"] = commit_id
    if branch:
       self.sources[0][source_type]["branch"] = branch
except:
    pass
```

2017-03-14 13:53 UTC, alanoe commented on lib/package.py
> +            if package.startswith(name):
Done

2017-03-14 14:15 UTC, alanoe commented on lib/package.py
> +                           self.sources[0][source_type]["commit_id"] = package_parts[2]
I indeed dislike EAFP, but I improved the code:
 - reduced if nesting a little
 - replaced self.sources[0][source_type] with a variable
 - tested if there are any sources

2017-03-14 14:34 UTC, alanoe commented on tools/build_packages.py
> +        packages_to_build_names.append(package.split("#")[0])
Done

2017-03-14 14:35 UTC, alanoe commented on lib/package.py
> +                    package_parts = package.split("#")
Done

2017-03-14 18:23 UTC, olavphibm commented
start build

2017-03-14 18:45 UTC, ghost requested changes

2017-03-14 18:45 UTC, olavphibm commented on lib/config.py
> +        if text.startswith('R|'):
Why `R|`?

2017-03-14 18:45 UTC, olavphibm commented on lib/package.py
> +                        main_source["src"] = package_parts[1]
`src` should also be updated when `package_parts` is 3 or 4.
I think you could remove this if `== 2` and use a `break` in `== 1`

2017-03-14 19:54 UTC, alanoe commented on lib/config.py
> +        if text.startswith('R|'):
A special "raw text" identifier, I used a constant instead.

2017-03-14 19:57 UTC, alanoe commented on lib/package.py
> +                        main_source["src"] = package_parts[1]
I still need to test if len == 2, if len >4 or something similar to be able to infer if number of parts is correct. IMHO testing each length is more readable.

2017-03-16 13:36 UTC, olavphibm commented
start tests

2017-03-16 13:54 UTC, olavphibm commented
start build

2017-03-16 16:23 UTC, ghost approved these changes

2017-03-17 18:36 UTC, farosas approved these changes

2017-03-17 18:37 UTC, merged