Fix mock incomplete output to log file
open-power-host-os/builds pull request #212
Opened 2017-03-10 14:07 UTC by gutoyr

2017-03-10 14:41 UTC, olavphibm commented on config.yaml
> +      --plugin-option=tmpfs:required_ram_mb=39800
Do you any idea how much disk space and RAM the ISO creation uses? Those values could probably be reduced.

2017-03-10 18:35 UTC, alanoe requested changes

2017-03-10 18:35 UTC, alanoe commented on config.yaml
> +      --plugin-option=tmpfs:required_ram_mb=39800
- I assume this change aims performance increase, pls document this in commit longer msg
- Certainly 32G for max FS size and 39800 MB for RAM is too much for ISO creation

2017-03-13 12:57 UTC, farosas approved these changes

2017-03-20 16:58 UTC, mopsfelder commented
Let's merge this and tune those numbers later.

Thanks, @gutoyr!

2017-03-20 17:02 UTC, merged