Reduce changelog on spec files on update_versions
open-power-host-os/builds pull request #223
Opened 2017-03-20 20:32 UTC by lisibann

Currently, when we update packages versions/releases, we mention in the changelog every commit that is included, with its short commit message. This makes the changelog very big, especially for some packages such as kernel, with information that is not very useful by its own.

2017-03-22 18:16 UTC, ghost requested changes

2017-03-22 18:16 UTC, olavphibm commented on tools/update_versions.py
> +                new_source["repo"], new_commit_id)
You could use the [commit function](http://gitpython.readthedocs.io/en/1.0.1/reference.html#git.repo.base.Repo.commit) and [summary attribute](http://gitpython.readthedocs.io/en/1.0.1/reference.html#git.objects.commit.Commit.summary) to make this much simpler and remove the functions `_get_git_last_commit_log` and `_get_git_log`:
```
SHORT_HEX_SHA_LENGTH = 7
commit = new_source["repo"].commit(new_commit_id)
change_log_lines += "Updating to commit %s: %s" % (
    commit.hexsha[:SHORT_HEX_SHA_LENGTH], commit.summary))

2017-03-22 18:23 UTC, farosas requested changes

2017-03-22 18:23 UTC, fabianorosas commented on tools/update_versions.py
> -            change_log_lines += _get_git_log(
The old function is not used anywhere else, afaics. It should be removed.

2017-03-22 18:23 UTC, fabianorosas commented on tools/update_versions.py
> +    for commit in repo.iter_commits():
Use `repo.commit` instead of iterating.

https://gitpython.readthedocs.io/en/stable/tutorial.html#the-commit-object

2017-03-22 18:23 UTC, fabianorosas commented on tools/update_versions.py
> +def _get_git_last_commit_log(repo, last_id):
I think we could make this function generic. It doesn't need to know that it is using the last commit. Maybe `_get_git_log` or `_get_git_commit_log` and then alter the `last_id` argument to `commit_id`.

2017-03-22 18:23 UTC, fabianorosas commented on tools/update_versions.py
> +    Get log of short SHA1 and short message for last commit
s/ last//

2017-03-22 18:24 UTC, fabianorosas commented on tools/update_versions.py
> +                new_source["repo"], new_commit_id)
@olavphibm what about the removal of quotes?

2017-03-22 18:33 UTC, olavphibm commented on tools/update_versions.py
> +                new_source["repo"], new_commit_id)
@fabianorosas Ok, that may be a reason to keep the function. Why do we need to remove quotes though?

2017-03-22 18:41 UTC, fabianorosas commented on tools/update_versions.py
> +                new_source["repo"], new_commit_id)
rpmdev-bumpspec going crazy maybe?

2017-03-22 20:13 UTC, lisibann commented on tools/update_versions.py
> +def _get_git_last_commit_log(repo, last_id):
done.

2017-03-22 20:14 UTC, lisibann commented on tools/update_versions.py
> +    Get log of short SHA1 and short message for last commit
done.

2017-03-22 20:14 UTC, lisibann commented on tools/update_versions.py
> -            change_log_lines += _get_git_log(
done.

2017-03-22 20:45 UTC, lisibann commented on tools/update_versions.py
> +    for commit in repo.iter_commits():
done

2017-03-22 20:49 UTC, farosas approved these changes

2017-03-23 13:03 UTC, lisibann commented on tools/update_versions.py
> +                new_source["repo"], new_commit_id)
partially done.

2017-03-23 14:13 UTC, ghost approved these changes

2017-03-23 14:15 UTC, merged