ae/move rpm creation to separate method
open-power-host-os/builds pull request #236
Opened 2017-03-30 20:32 UTC by alanoe

2017-03-31 00:49 UTC, mopsfelder commented on lib/mockbuilder.py
> +        Prepare package source files
Perhaps we can briefly explain what actions are done in order to prepare the sources.  Example:

```python
def prepare_sources(self, package):
    """
    Create directory structure, create a tarball with the source code,
    and copy files to chroot.
    """
```

2017-03-31 00:52 UTC, mopsfelder commented on lib/mockbuilder.py
> +            package (str): package name
There is no `package` parameter to be documented, only `self`.

2017-03-31 18:15 UTC, ghost requested changes

2017-03-31 18:15 UTC, olavphibm commented on lib/mockbuilder.py
> +        LOG.info(msg)
Could you move this log to inside `_build_rpm`? It does not make much sense to surround `_copy_rpms` with these lines.

2017-03-31 18:15 UTC, olavphibm commented on lib/mockbuilder.py
> +            package (str): package name
This is not a `str`, it's an `RPM_Package` object.
This applies for all methods of this class.

2017-04-03 13:09 UTC, fabianorosas commented
LGTM

start build

2017-04-05 17:50 UTC, alanoe commented on lib/mockbuilder.py
> +        LOG.info(msg)
Done

2017-04-05 17:50 UTC, alanoe commented on lib/mockbuilder.py
> +            package (str): package name
Done

2017-04-05 17:50 UTC, alanoe commented on lib/mockbuilder.py
> +        Prepare package source files
Done

2017-04-05 17:52 UTC, alanoe commented on lib/mockbuilder.py
> +            package (str): package name
Done

2017-04-06 15:42 UTC, ghost approved these changes

2017-04-06 15:43 UTC, merged