Organize directory structure of builds repository
open-power-host-os/builds pull request #247
Opened 2017-04-24 18:41 UTC by YasminBeatriz

Organize directory structure of builds repository

- Move ``tools/*.py`` to ```lib/subcommands/*.py``` and delete ```tools/``` directory.

- Create new directory ```scripts/``` and move ```validate_*.py``` to ```scripts/```.

- Update Jenkins jobs to use new path ```scripts/validate_*.py```.

- Move directory ```mock_configs/``` to ```config/mock/```.

- Move ```config.yaml``` from the root to ```config/host_os.yaml```.

2017-04-24 19:10 UTC, ghost requested changes
The paths to mock config files need to be updated in `config/host_os.yaml`

2017-04-24 19:12 UTC, olavphibm commented
ok to test

2017-04-25 12:02 UTC, olavphibm commented
start tests

2017-04-25 12:06 UTC, ghost submitted a review, later dismissed
The build is failing because we need to apply the changes in the infrastructure repo.

Minor: there's no need to repeat the commit short message in the commit longer message.

2017-04-25 17:54 UTC, ghost approved these changes

2017-04-25 17:59 UTC, ghost submitted a review, later dismissed

2017-04-25 17:59 UTC, olavphibm commented on BUILD_OLD_VERSIONS.md
> +$ sed -i 's|http://mirror.centos.org/altarch/|http://vault.centos.org/altarch/7.2.1511/|' configs/mock/CentOS/7/CentOS-7-ppc64le.cfg
Remove the "s" from "configs"

2017-04-25 17:59 UTC, olavphibm commented on BUILD_OLD_VERSIONS.md
> +$ sed -i -E "s|  '7': (\"\./configs/mock.*)|  '7.2': \1|" config/host_os.yaml
Remove the "s" from "configs"

2017-04-27 12:18 UTC, olavph approved these changes

2017-04-27 15:20 UTC, merged