Allow automatic updating of spec files version and release fields
open-power-host-os/builds pull request #96
Opened 2016-10-19 17:07 UTC by fabianorosas

2016-10-19 17:08 UTC, maurorodrigues commented
Can one of the admins verify this patch?

2016-10-19 17:24 UTC, fabianorosas commented
Depends on https://github.com/open-power-host-os/versions/pull/43

2016-10-19 17:30 UTC, fabianorosas commented
Just a heads-up to anyone testing this, the script still needs to have the components directory alrady present. I'll alter it to clone the versions repo if it is not found but it will require some refactoring in host-os-build.py so it might take a bit of time.

2016-10-19 19:18 UTC, fabianorosas commented on upgrade_versions.py
> +            version = re.search(r'Version:\s*(\S+)', content).groups(1)[0]
This will always work, but it is wrong. It should be `.group(1)` instead of `.groups(1)[0]`

2016-10-21 19:04 UTC, ghost requested changes

2016-10-21 19:04 UTC, ghost commented on upgrade_versions.py
> +            ('%s.spec' % self.pkg, r'Version:(.*)'),
There might be whitespaces after ":":  `r'Version:\s*(.*)'`

2016-10-21 19:04 UTC, ghost commented on upgrade_versions.py
> +            msg = "Could not find %s's version in the source repo." % self.pkg
You could pass this msg to LOG.error

2016-10-21 19:04 UTC, ghost commented on upgrade_versions.py
> +            ('VERSION', r'.*'),
Enclose in parenthesis so it matches a group

2016-10-21 19:04 UTC, ghost commented on upgrade_versions.py
> +                    match.group().strip())
You don't need the "or" if the regex has parenthesis.

2016-10-21 19:04 UTC, ghost commented on upgrade_versions.py
> +                msg += " Try specifying version_file_regex in the .yaml file."
`" Try specifying version file and regex in the .yaml file."`
They are separate variables in the yaml file.

2016-10-21 19:04 UTC, ghost commented on upgrade_versions.py
> +        version_regexes = [
I'd name this `version_files_and_regexes`

2016-10-21 19:04 UTC, ghost commented on upgrade_versions.py
> +        pkg.commit_id = pkg.repository.repo.head.target.hex[:7]
If commit_id hasn't changed, you don't need to do anything:

```
if pkg.commit_id != self.pkg.commit_id:
  LOG.debug("No changes for package %s", pkg.name)
  return
```

2016-10-24 12:17 UTC, fabianorosas commented on upgrade_versions.py
> +            ('%s.spec' % self.pkg, r'Version:(.*)'),
That was on purpose because I'm using `str.strip()` later on, but I guess there's no harm in changing it.

2016-10-24 12:17 UTC, fabianorosas commented on upgrade_versions.py
> +                    match.group().strip())
Yes. I was again trying to keep thinks flexible but perhaps there's no real benefit in not using groups.

2016-10-24 12:17 UTC, fabianorosas commented on upgrade_versions.py
> +                msg += " Try specifying version_file_regex in the .yaml file."
Yep, and the commit message is wrong too.

2016-10-25 13:39 UTC, ghost approved these changes

2016-10-25 16:00 UTC, maurorodrigues approved these changes

2016-10-25 18:33 UTC, fabianorosas commented
skip ci

2016-10-25 18:35 UTC, fabianorosas commented
start tests

2016-10-25 23:58 UTC, maurorodrigues commented
@fabianorosas Does this depends on something other than open-power-host-os/versions#43 right now??

2016-10-26 11:44 UTC, fabianorosas commented
> @fabianorosas Does this depends on something other than open-power-host-os/versions#43 right now??

No, it doesn't. I have one more change about cloning the versions repo ready to send but it is an improvement on what we already have today. It also depends on this on so it would be good to merge it first.

2016-11-04 13:38 UTC, merged